# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET - Firefly build 

on:
  push:
    branches: [ "main", "service-next" ]
  pull_request:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Firefly/Firefly.sln
    - name: Build
      run: dotnet build ./Firefly/Firefly.sln --no-restore
    - name: Unit Tests
      run: dotnet test --no-restore --verbosity normal
